# Generated by Django 5.0.7 on 2024-09-25 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', 'add_slug_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip_code',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
